change git log formatting and improves date validation

diff --git a/pkm85/bin/pkm85 b/pkm85/bin/pkm85
--- a/pkm85/bin/pkm85
+++ b/pkm85/bin/pkm85
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Pkm85.sh
-# Version: 0.85.1
+# Version: 0.85.2
 # author: Marselo Maciel
 # e-mail: falso.endereco@gmail.com
 # date: dez/2022
@@ -15,7 +15,7 @@
 ##############################################################################
 #
 # check if current directory is a git repository
-script_info="Pkm85 - Version 0.85.1 - What is Pkm 85?"
+script_info="Pkm85 - Version 0.85.2 - What is Pkm 85?"
 disclaimer='Pkm85 é apenas um facilitador. Você é o único responsável por utilizar as informações fornecidas.'
 echo -e $script_info'\n'
 
@@ -30,25 +30,6 @@ short_help() {
 check_for_man_page() {
     man "$1" >/dev/null 2>&1
 }
-
-# check/handle arguments
-if [[ "$1" = "-g" || "$1" = "--gui" || -z "$1" ]]; then
-    gui_interface=true
-elif [[ "$1" = "-t" || "$1" = "--terminal" ]]; then
-    gui_interface=false
-elif [[ "$1" = "-h" || "$1" = "--help" || "$1" = "-?" ]]; then
-    man_page_check=$(check_for_man_page $0 && echo 0)
-
-    if [[ $man_page_check = 0 ]]; then
-        man "$0"
-    else
-        short_help
-    fi
-    exit 0
-else
-    echo 'Opção inválida. Para ajuda utilize pkm85 -h'
-    exit 1
-fi
 
 whiptail_error() {
     whiptail --ok-button "Encerrar" --backtitle "$script_info" --title "Erro!" --msgbox "$1" 8 55
@@ -65,8 +46,19 @@ is_valid_date() {
         exit 1
     fi
 
-    if [[ $1 != $(date -d "$1" '+%Y-%m-%d') ]]; then
-        error_message='Data ou formato inválido: '$1
+    if [[ $1 =~ ^[2]{1}[0]{1}[0-9]{2}-[0-9]{2}-[0-9]{2}$ ]] && date -d "$1" >/dev/null; then
+
+        if [[ $1 != $(date -d "$1" '+%Y-%m-%d') ]]; then
+            error_message='Data ou formato inválido: '$1
+            if [ "$gui_interface" = true ]; then
+                whiptail_error "$error_message"
+            else
+                echo -e 'Erro: '$error_message
+            fi
+            exit 1
+        fi
+    else
+        error_message="Data $1 não está no formato YYYY-MM-DD"
         if [ "$gui_interface" = true ]; then
             whiptail_error "$error_message"
         else
@@ -114,6 +106,25 @@ terminal_interface() {
 
 }
 
+# check/handle arguments
+if [[ "$1" = "-g" || "$1" = "--gui" || -z "$1" ]]; then
+    gui_interface=true
+elif [[ "$1" = "-t" || "$1" = "--terminal" ]]; then
+    gui_interface=false
+elif [[ "$1" = "-h" || "$1" = "--help" || "$1" = "-?" ]]; then
+    man_page_check=$(check_for_man_page $0 && echo 0)
+
+    if [[ $man_page_check = 0 ]]; then
+        man "$0"
+    else
+        short_help
+    fi
+    exit 0
+else
+    echo 'Opção inválida. Para ajuda utilize pkm85 -h'
+    exit 1
+fi
+
 # Pkm85 must be called in a directory that is a git repository
 if [ $(
     git -C . rev-parse 2>/dev/null
@@ -151,6 +162,16 @@ else
     terminal_interface
 fi
 
+if [[ "$inicio" > "$fim" ]]; then
+    error_message="Data inicial ($inicio) maior que data final ($fim)"
+    if [ "$gui_interface" = true ]; then
+        whiptail_error "$error_message"
+    else
+        echo -e '\nErro: '$error_message
+    fi
+    exit 1
+fi
+
 #salva dados informados
 echo "$autor;$inicio;$fim" >$input
 
@@ -166,7 +187,7 @@ nodupsfile=$outPutDirectory/$timestamp'b-no-dups.txt'
 dupsFile=$outPutDirectory/$timestamp'c-dups.txt'
 
 # executa git log
-git log --oneline --name-status --no-merges --since="$inicio - 1 day" --until=$fim --author="$autor" >$gitLogOutPutFile
+git log --name-status --pretty="format:%h %ad %s" --date=format:"%F %H:%M" --no-merges --since="$inicio - 1 day" --until=$fim --author="$autor" >$gitLogOutPutFile
 
 #Verifica se o arquivo não está vazio
 qtLinhas=$(awk 'END { print NR }' $gitLogOutPutFile)
@@ -202,4 +223,3 @@ echo -e $sucess_info
 echo -e $warning1
 
 exit 0
-
