rewrite man page

diff --git a/pkm85/bin/pkm85 b/pkm85/bin/pkm85
--- a/pkm85/bin/pkm85
+++ b/pkm85/bin/pkm85
@@ -1,23 +1,22 @@
 #!/bin/bash
 # Pkm85.sh
-# Version: 0.85.2
+# Version: 0.85.3
 # author: Marselo Maciel
 # e-mail: falso.endereco@gmail.com
 # date: dez/2022
 # License: GPLv3
 #
 # [en]
-# What this script does? It runs 'git log' to get all modified files by given author within a given period of time
+# What this script does? It runs 'git log' to get all added/modified files by given author within a given period of time
 #
 # [pt_br]
-# O que este script faz? Executa 'git log' para buscar todos os arquivos modificados pelo autor informado em um determinado período
+# O que este script faz? Executa 'git log' para buscar todos os arquivos criados/modificados pelo autor informado em um determinado período
 #
 ##############################################################################
 #
 # check if current directory is a git repository
-script_info="Pkm85 - Version 0.85.2 - What is Pkm 85?"
+script_info="Pkm85 - Version 0.85.3 - What is Pkm 85?"
 disclaimer='Pkm85 é apenas um facilitador. Você é o único responsável por utilizar as informações fornecidas.'
-echo -e $script_info'\n'
 
 short_help() {
     echo 'Options '
@@ -58,7 +57,7 @@ is_valid_date() {
             exit 1
         fi
     else
-        error_message="Data $1 não está no formato YYYY-MM-DD"
+        error_message="Data $1 não está no formato 20YY-MM-DD"
         if [ "$gui_interface" = true ]; then
             whiptail_error "$error_message"
         else
@@ -69,11 +68,28 @@ is_valid_date() {
 
 }
 
+validate_author_name() {
+    if [ -z "$autor" ]; then
+        error_message='Nome do dev não informado'
+        if [ "$gui_interface" = true ]; then
+            whiptail_error "$error_message"
+            exit 1
+        else
+            if [ -z "$fautor" ]; then
+                echo -e 'Erro: '$error_message
+                exit 1
+            else
+                autor=$fautor
+            fi
+        fi
+    fi
+}
+
 whiptail_interface() {
     whiptail --ok-button "Ok, Entendi" --backtitle $script_info --title "D I S C L A I M E R" --msgbox "$disclaimer" 8 60
 
     autor=$(whiptail --ok-button "Continuar" --nocancel --backtitle $script_info --title "Autor" --inputbox "Informe nome, matrícula ou e-mail do Desenvolvedor" 9 40 $fautor 3>&1 1>&2 2>&3)
-
+    validate_author_name
     inicio=$(whiptail --ok-button "Continuar" --nocancel --backtitle $script_info --title "Data Inicial" --inputbox "Informe a data inicial no formato AAAA-MM-DD" 9 40 $finicio 3>&1 1>&2 2>&3)
     is_valid_date $inicio
     fim=$(whiptail --ok-button "Continuar" --nocancel --backtitle $script_info --title "Data final" --inputbox "Informe a data final no formato AAAA-MM-DD" 9 40 $ffim 3>&1 1>&2 2>&3)
@@ -81,18 +97,18 @@ whiptail_interface() {
 }
 
 terminal_interface() {
-    echo -e "\nInforme os campos solicitados ou tecle Enter para repetir os valores da última execução"
-    read -p "  Nome ou e-mail do committer ($fautor): " autor
+    echo -e "\nInforme ou tecle Enter para confirmar"
+    read -p "  Nome ou e-mail do dev ($fautor): " autor
     if [ -z "$autor" ]; then
         if [ -z "$fautor" ]; then
-            echo 'Nome do committer não informado'
+            echo 'Nome do dev não informado'
             exit 1
         else
             autor=$fautor
         fi
     fi
     #
-    read -p "  Data inicial no formato AAAA-MM-DD ($finicio)]: " inicio
+    read -p "  Data inicial no formato AAAA-MM-DD ($finicio): " inicio
     if [ -z "$inicio" ]; then
         inicio=$finicio
     fi
@@ -111,6 +127,9 @@ if [[ "$1" = "-g" || "$1" = "--gui" || -z "$1" ]]; then
     gui_interface=true
 elif [[ "$1" = "-t" || "$1" = "--terminal" ]]; then
     gui_interface=false
+elif [[ "$1" = "-v" || "$1" = "--version" ]]; then
+    echo -e $script_info
+    exit 0
 elif [[ "$1" = "-h" || "$1" = "--help" || "$1" = "-?" ]]; then
     man_page_check=$(check_for_man_page $0 && echo 0)
 
@@ -124,6 +143,8 @@ else
     echo 'Opção inválida. Para ajuda utilize pkm85 -h'
     exit 1
 fi
+
+echo -e $script_info
 
 # Pkm85 must be called in a directory that is a git repository
 if [ $(
@@ -187,7 +208,7 @@ nodupsfile=$outPutDirectory/$timestamp'b-no-dups.txt'
 dupsFile=$outPutDirectory/$timestamp'c-dups.txt'
 
 # executa git log
-git log --name-status --pretty="format:%h %ad %s" --date=format:"%F %H:%M" --no-merges --since="$inicio - 1 day" --until=$fim --author="$autor" >$gitLogOutPutFile
+git log --author="$autor" --since="$inicio - 1 day" --until=$fim --no-merges --name-status --pretty="format:%h %ad %s" --date=format:"%F %H:%M" >$gitLogOutPutFile
 
 #Verifica se o arquivo não está vazio
 qtLinhas=$(awk 'END { print NR }' $gitLogOutPutFile)
